import os
from dotenv import load_dotenv

load_dotenv()

META_ACCESS_TOKEN = os.getenv("META_ACCESS_TOKEN")
META_AD_ACCOUNT_ID = os.getenv("META_AD_ACCOUNT_ID")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
GOOGLE_DEVELOPER_TOKEN = os.getenv("GOOGLE_DEVELOPER_TOKEN")
GOOGLE_CUSTOMER_ID = os.getenv("GOOGLE_CUSTOMER_ID")
GOOGLE_REFRESH_TOKEN = os.getenv("GOOGLE_REFRESH_TOKEN")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GA4_PROPERTY_ID = os.getenv("GA4_PROPERTY_ID")
NAVER_API_KEY = os.getenv("NAVER_API_KEY")
NAVER_SECRET_KEY = os.getenv("NAVER_SECRET_KEY")
NAVER_CUSTOMER_ID = os.getenv("NAVER_CUSTOMER_ID")
GSC_SITE_URLS = os.getenv("GSC_SITE_URLS", "").split(",")